# Change ALL of this before going to production using this template. Do not expose yourself!
# You should probably get these from something like GH Secrets and add them, but for testing this can work.
# to get a string like this run:
# openssl rand -hex 32

SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
OPENROUTER_SECRET = ""